### PR TITLE
Strip stack trace line in errors.Ex

### LINKED ISSUE #14: Strip last stack trace line in errors.Ex
Structure errors.Ex contains an error and a stack trace, but when created with errors.AsEx(err) the stack trace has an additional last line inside AsEx() which should be cut off.

### PR DESCRIPTION
**Pull request by GeniyX**
Close #14

### CODE REVIEW

File: errors/errors.go [hunk 1]
```diff
@@ -12,6 +12,38 @@ func New(text string) error {
 	return errors.New(text)
 }
 
+// Stack returns a formatted stack trace of the goroutine that calls it.
+// The argument skip is the number of stack frames to ascend
+func Stack(i int) string {
+	// code from "runtime/debug"
+	// if call debug.Stack() it add 2 lines to end
```
Comment (Monnoroch) [inline errors/errors.go]: Remove this line, even I didn't understand what does it mean.

Comment (GeniyX) [inline errors/errors.go]: Done
